// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwVpg1MPy_RIF-WjJovpD3KGpDof3VKb0',
    appId: '1:938061275492:web:581037e66f83d401b41a71',
    messagingSenderId: '938061275492',
    projectId: 'faxinex-31894',
    authDomain: 'faxinex-31894.firebaseapp.com',
    storageBucket: 'faxinex-31894.appspot.com',
    measurementId: 'G-G1QRVHPC9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOFBjK2udnbZG1YOuTSgLiQ8ZdmI1vTeQ',
    appId: '1:938061275492:android:9bcf4e28e7a1148db41a71',
    messagingSenderId: '938061275492',
    projectId: 'faxinex-31894',
    storageBucket: 'faxinex-31894.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVhS4NdYYtQU8N3U3ywhGFa7rxtAFNaDc',
    appId: '1:938061275492:ios:f8b92d1e547bd033b41a71',
    messagingSenderId: '938061275492',
    projectId: 'faxinex-31894',
    storageBucket: 'faxinex-31894.appspot.com',
    iosBundleId: 'com.faxinex.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVhS4NdYYtQU8N3U3ywhGFa7rxtAFNaDc',
    appId: '1:938061275492:ios:f8b92d1e547bd033b41a71',
    messagingSenderId: '938061275492',
    projectId: 'faxinex-31894',
    storageBucket: 'faxinex-31894.appspot.com',
    iosBundleId: 'com.faxinex.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwVpg1MPy_RIF-WjJovpD3KGpDof3VKb0',
    appId: '1:938061275492:web:9287dcdba9abcc60b41a71',
    messagingSenderId: '938061275492',
    projectId: 'faxinex-31894',
    authDomain: 'faxinex-31894.firebaseapp.com',
    storageBucket: 'faxinex-31894.appspot.com',
    measurementId: 'G-T57HW72FS5',
  );
}
